### ISSUE TITLE
Uhm build fails?

### ISSUE THREAD

**Issue by MrFaul** [chronotope/chrono#1380]
Something is wrong, the lint doesn't compile, can somebody check that please?
It's not fun to see red failing badges.

**Comment by jtmoon79** [comment]
I could not find failed builds here on github under the _Actions_ tab.  But I did find [this build failure at docs.rs](https://docs.rs/crate/chrono/0.4.32/builds/1098853)

```
...
[INFO] [stderr] warning: Target filter specified, but no targets matched. This is a no-op
[INFO] [stderr]     Checking rkyv v0.7.43
[INFO] [stderr] error: one of ["size_16", "size_32", or "size_64"] features must be enabled
[INFO] [stderr]    --> /opt/rustwide/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.43/src/macros.rs:114:1
[INFO] [stderr]     |
[INFO] [stderr] 114 | core::compile_error!(r#"one of ["size_16", "size_32", or "size_64"] features must be enabled"#);
[INFO] [stderr]     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stderr] 
[INFO] [stderr] error: cannot find macro `pick_size_type` in this scope
[INFO] [stderr]    --> /opt/rustwide/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.43/src/lib.rs:723:23
...
```

At first glance, this looks to be an rkyv oddity.
Tag #644 and @dovahcrow

**Comment by dovahcrow** [comment]
I failed to reproduce locally. Here's what I ran:
`cargo +nightly rustdoc --lib -Zrustdoc-map --all-features`.
Rust version: v1.77.0-nightly

**Comment by pitdicker** [comment]
Fixed with 0.4.33 in https://github.com/chronotope/chrono/pull/1383. Thank you for reporting, and @jtmoon79 for investigating.

**Comment by jtmoon79** [comment]
Thanks @dovahcrow for following up too.

**Comment by MrFaul** [comment]
Thanks for fixing.

A small issue remains so:
![Screenshot_20240126-080546](https://github.com/chronotope/chrono/assets/3279164/4d98de61-e4ef-440e-b3b2-0bc01cd12abf)
All tests and builds are still failing at least according to the badge...
But I think there is something wrong with job naming and not the testing it self.

Since chrono is a very popular crate I think this isn't something that should left that way.
Even removing the badge is a better option.

**Comment by djc** [comment]
That's from the main branch, whereas we mostly release from the 0.4.x branch. The badge should fix itself when we do our next merge from 0.4.x to main. Perhaps we should rename main to 0.5.x and keep 0.4.x as main?

**Comment by MrFaul** [comment]
Would be better if the "landing page" is actually the current published version.
After all the same badges are also shown in the docs.

**Comment by pitdicker** [comment]
> Perhaps we should rename main to 0.5.x and keep 0.4.x as main?

I'm all for it. We would have to change the target branch of all open PRs though.

**Comment by pitdicker** [comment]
I can't find the reason why the badge is still red but made an attempt in https://github.com/chronotope/chrono/pull/1388.

**Comment by pitdicker** [comment]
> > Perhaps we should rename main to 0.5.x and keep 0.4.x as main?
> 
> I'm all for it. We would have to change the target branch of all open PRs though.

@djc I don't have permission, but it may just work when you rename the branches via the GitHub interface.

**Comment by djc** [comment]
Done -- let's use #1390 to coordinate any necessary changes in the repo contents.

**Comment by pitdicker** [comment]
Should we yank 0.4.32?

**Comment by djc** [comment]
Nah, it doesn't seem bad enough for that.

**Comment by MrFaul** [comment]
Nice 👍🏼
Looooks way better this way.
Thx for fixing it.
